export const additional16ProductRepos = [
  {
    slug: "hotel-price-watch",
    category: "hotel",
    emoji: "🏨",
    label: "宿泊空室・値下げアラート",
    sublabel: "エリアと上限金額を保存して、空室と値下げの瞬間を逃さない。",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    badge: "買い切り ZIP",
    title: "Hotel Price Watch｜宿泊空室・値下げアラート",
    description: "エリアと上限金額を保存して、空室と値下げの瞬間を逃さない。 出張・旅行で今安い／空いている宿を即取りたい人向け。",
    features: [
      "エリア・日程・上限金額のウォッチ登録",
      "空室・値下げシードの条件一致表示",
      "保存ウォッチのローカル管理",
      "予約アフィ／有料通知への導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/hotel-price-watch",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-hotel-price-watch/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-hotel-price-watch",
    recommendRank: 1,
    ideaId: "hotel-price-watch",
  },
  {
    slug: "job-match-alert",
    category: "life-learn",
    emoji: "💼",
    label: "求人条件一致通知",
    sublabel: "希望条件を一度保存すれば、一致した求人だけを追える。",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "買い切り ZIP",
    title: "Job Match Alert｜求人条件一致通知",
    description: "希望条件を一度保存すれば、一致した求人だけを追える。 転職活動を通知で回したい人（新着・締切・面接枠）向け。",
    features: [
      "職種・年収・勤務地・リモート条件",
      "新着・締切・面接枠の一致表示",
      "保存条件のローカル管理",
      "後の採用媒体・人材紹介課金へ接続"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/job-match-alert",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-job-match-alert/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-job-match-alert",
    recommendRank: 2,
    ideaId: "job-match-alert",
  },
  {
    slug: "subsidy-alert-hub",
    category: "b2b",
    emoji: "📋",
    label: "補助金・助成金期限通知",
    sublabel: "締切が命の補助金を、期限順で見逃さない。",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)",
    badge: "買い切り ZIP",
    title: "Subsidy Alert Hub｜補助金・助成金期限通知",
    description: "締切が命の補助金を、期限順で見逃さない。 個人事業主・小規模事業者（期限が命）向け。",
    features: [
      "制度名・対象・締切の一覧",
      "残り日数ソート",
      "ウォッチ登録",
      "士業相談への橋渡し枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/subsidy-alert-hub",
    price: "¥2,480",
    priceNote: "¥2,480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-subsidy-alert-hub/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-subsidy-alert-hub",
    recommendRank: 3,
    ideaId: "subsidy-alert-hub",
  },
  {
    slug: "nearqueue",
    category: "b2b",
    emoji: "🎟️",
    label: "受付番号・待ち時間システム",
    sublabel: "近くの店舗で番号を取り、待ち時間を自分の時間に変える。",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2Bデモ＋案内",
    title: "NearQueue｜受付番号・待ち時間システム",
    description: "近くの店舗で番号を取り、待ち時間を自分の時間に変える。 美容・飲食・医療など、順番待ちを改善したい店舗向け。",
    features: [
      "来店者の受付番号発行（デモ）",
      "待ち組数・目安時間",
      "スタッフボード（呼び出し／案内済）",
      "受付後のクーポン枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/nearqueue",
    price: "¥3,800",
    priceNote: "¥3,800（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-nearqueue/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-nearqueue",
    recommendRank: 4,
    ideaId: "nearqueue",
  },
  {
    slug: "work-bar-navi",
    category: "hobby",
    emoji: "🌃",
    label: "夜のお店／仕事／エリアナビ",
    sublabel: "エリア×業態で、夜の仕事とお店を一本のナビにする。",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "買い切り ZIP",
    title: "Work Bar Navi｜夜のお店／仕事／エリアナビ",
    description: "エリア×業態で、夜の仕事とお店を一本のナビにする。 夜勤・短時間・飲み／仕事導線をまとめたい層向け。",
    features: [
      "エリア・業態フィルター",
      "求人／店舗カード",
      "スポンサー枠のプレースホルダ",
      "送客・掲載課金の導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/work-bar-navi",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-work-bar-navi/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-work-bar-navi",
    recommendRank: 5,
    ideaId: "work-bar-navi",
  },
  {
    slug: "midnight-spot-alert",
    category: "hotel",
    emoji: "🌙",
    label: "終電後スポット通知",
    sublabel: "終電を逃した夜に、休憩・食事・仮眠の候補をすぐ出す。",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    badge: "買い切り ZIP",
    title: "Midnight Spot Alert｜終電後スポット通知",
    description: "終電を逃した夜に、休憩・食事・仮眠の候補をすぐ出す。 終電後の休憩／食事／仮眠を探す人向け。",
    features: [
      "駅・種別（休憩／食事／仮眠）",
      "終電後スポットのシード検索",
      "ウォッチ保存",
      "終電ホテルへの送客"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/midnight-spot-alert",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-midnight-spot-alert/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-midnight-spot-alert",
    recommendRank: 6,
    ideaId: "midnight-spot-alert",
  },
  {
    slug: "welfare-job-alert",
    category: "life-learn",
    emoji: "🤝",
    label: "福祉系求人通知",
    sublabel: "福祉・障害者雇用に特化した条件一致だけを追う。",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "買い切り ZIP",
    title: "Welfare Job Alert｜福祉系求人通知",
    description: "福祉・障害者雇用に特化した条件一致だけを追う。 障害者雇用・福祉領域の就職／採用向け。",
    features: [
      "職種・雇用形態・配慮条件",
      "事業所シードの一致表示",
      "求職者ウォッチ",
      "事業所掲載枠（準備）"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/welfare-job-alert",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-welfare-job-alert/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-welfare-job-alert",
    recommendRank: 7,
    ideaId: "welfare-job-alert",
  },
  {
    slug: "busstay",
    category: "hotel",
    emoji: "🚌",
    label: "バス到着後の宿探し",
    sublabel: "到着バスターミナルから徒歩圏の宿だけを出す。",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    badge: "買い切り ZIP",
    title: "BusStay｜バス到着後の宿探し",
    description: "到着バスターミナルから徒歩圏の宿だけを出す。 高速バス到着後に近い宿を即探したい人向け。",
    features: [
      "到着地点の選択",
      "徒歩分数での絞り込み",
      "今夜空きシード",
      "宿泊予約アフィ導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/busstay",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-busstay/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-busstay",
    recommendRank: 8,
    ideaId: "busstay",
  },
  {
    slug: "trip-route-stay",
    category: "hotel",
    emoji: "🗺️",
    label: "移動×宿×スポットの旅ルート支援",
    sublabel: "移動・宿・ローカルスポットを1本の旅程にする。",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "買い切り ZIP",
    title: "Trip Route Stay｜移動×宿×スポットの旅ルート支援",
    description: "移動・宿・ローカルスポットを1本の旅程にする。 旅のルート設計を効率化したい人向け。",
    features: [
      "出発・到着・日数の入力",
      "スポット＋宿のテンプレ旅程",
      "コピー用 itinerary",
      "宿泊・スポットの monetization 枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/trip-route-stay",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-trip-route-stay/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-trip-route-stay",
    recommendRank: 9,
    ideaId: "trip-route-stay",
  },
  {
    slug: "open-close-radar",
    category: "hobby",
    emoji: "📡",
    label: "開店閉店レーダー＋通知",
    sublabel: "近所の開店・閉店を、UGCと通知で速報する。",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "買い切り ZIP",
    title: "Open/Close Radar｜開店閉店レーダー＋通知",
    description: "近所の開店・閉店を、UGCと通知で速報する。 地域の開店閉店速報を追う生活者＋露出したい店舗向け。",
    features: [
      "地域の開店／閉店シード",
      "UGC投稿（ローカル保存）",
      "ウォッチ",
      "店舗掲載・スポンサー枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/open-close-radar",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-open-close-radar/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-open-close-radar",
    recommendRank: 10,
    ideaId: "open-close-radar",
  },
  {
    slug: "comicstay",
    category: "hobby",
    emoji: "📚",
    label: "漫画喫茶／ネットカフェ UGC検索",
    sublabel: "個室・シャワー・深夜滞在。条件で漫画喫茶を探す。",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "買い切り ZIP",
    title: "ComicStay｜漫画喫茶／ネットカフェ UGC検索",
    description: "個室・シャワー・深夜滞在。条件で漫画喫茶を探す。 個室・シャワー・深夜滞在などの条件で探したい人向け。",
    features: [
      "個室／シャワー／深夜のフィルター",
      "UGCメモ",
      "施設カード",
      "掲載・キーワード広告枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/comicstay",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-comicstay/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-comicstay",
    recommendRank: 11,
    ideaId: "comicstay",
  },
  {
    slug: "my-dartslive",
    category: "hobby",
    emoji: "🎯",
    label: "ダーツ施設横断 UGC",
    sublabel: "大会・クーポン・深夜。ダーツ施設を横断して探す。",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "買い切り ZIP",
    title: "My Dartslive｜ダーツ施設横断 UGC",
    description: "大会・クーポン・深夜。ダーツ施設を横断して探す。 大会／クーポン／深夜営業などで施設を探す層向け。",
    features: [
      "施設条件フィルター",
      "大会・クーポン・深夜タグ",
      "UGC",
      "施設掲載課金枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/my-dartslive",
    price: "¥2,480",
    priceNote: "¥2,480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-my-dartslive/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-my-dartslive",
    recommendRank: 12,
    ideaId: "my-dartslive",
  },
  {
    slug: "eki-genre-map",
    category: "hobby",
    emoji: "🚉",
    label: "駅×ジャンルのローカル発見マップ",
    sublabel: "駅名とジャンルを選ぶだけで、近場の候補が出る。",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "買い切り ZIP",
    title: "Eki Genre Map｜駅×ジャンルのローカル発見マップ",
    description: "駅名とジャンルを選ぶだけで、近場の候補が出る。 近場で何があるかを駅から探したい人向け。",
    features: [
      "駅×ジャンルのマトリクス",
      "スポットカード",
      "お気に入り保存",
      "ローカル広告・掲載枠"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/eki-genre-map",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-eki-genre-map/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-eki-genre-map",
    recommendRank: 13,
    ideaId: "eki-genre-map",
  },
  {
    slug: "content-brief-packs",
    category: "content",
    emoji: "📝",
    label: "業界別コンテンツブリーフ素材集",
    sublabel: "業界別テンプレで、ブリーフをすぐ書き出せる。",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "買い切り ZIP",
    title: "Content Brief Packs｜業界別コンテンツブリーフ素材集",
    description: "業界別テンプレで、ブリーフをすぐ書き出せる。 不動産／転職／飲食の記事を量産したい個人向け。",
    features: [
      "不動産・転職・飲食の3パック",
      "見出し・検索意図・CTAの雛形",
      "コピー出力",
      "シリーズ追加販売"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/content-brief-packs",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-content-brief-packs/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-content-brief-packs",
    recommendRank: 14,
    ideaId: "content-brief-packs",
  },
  {
    slug: "seo-dashboard-agency",
    category: "seo-ops",
    emoji: "📊",
    label: "SEO管理ダッシュボード Agency",
    sublabel: "顧客ごとの順位・指摘・月次レポを1画面に。",
    gradient: "linear-gradient(135deg, #15803d 0%, #14532d 100%)",
    badge: "B2Bデモ＋案内",
    title: "SEO Dashboard Agency｜SEO管理ダッシュボード Agency",
    description: "顧客ごとの順位・指摘・月次レポを1画面に。 複数サイト／複数顧客のSEOを見る個人と制作会社向け。",
    features: [
      "複数顧客カード",
      "仮想の順位・流入サマリー",
      "指摘チケット",
      "月次レポート下書き"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/seo-dashboard-agency",
    price: "¥3,800",
    priceNote: "¥3,800（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-seo-dashboard-agency/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-seo-dashboard-agency",
    recommendRank: 15,
    ideaId: "seo-dashboard-agency",
  },
  {
    slug: "room-ops-tickets",
    category: "affiliate",
    emoji: "🛠️",
    label: "楽天ROOM 週次改善チケット",
    sublabel: "週次で投稿・差し替えを1チケットずつ頼める。",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "PPVチケット",
    title: "ROOM Ops Tickets｜楽天ROOM 週次改善チケット",
    description: "週次で投稿・差し替えを1チケットずつ頼める。 ROOMツール購入者で、投稿の差し替えを任せたい人向け。",
    features: [
      "改善チケットの申込フォーム",
      "作業範囲のチェックリスト",
      "見積が立てやすい1回 ¥4,800",
      "ROOMツールへのアップセル"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/room-ops-tickets",
    price: "¥4,800",
    priceNote: "¥4,800（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: "https://syunnjack.github.io/chitamaru-room-ops-tickets/",
    trialLabel: "デモを見る",
    repoUrl: "https://github.com/syunnjack/chitamaru-room-ops-tickets",
    recommendRank: 16,
    ideaId: "room-ops-tickets",
  }
] as const
