export interface StoreProduct {
  slug: string
  category: string
  emoji: string
  label: string
  sublabel: string
  gradient: string
  badge: string
  title: string
  description: string
  features: string[]
  boothUrl: string
  price: string
  priceNote: string
  trialUrl: string | null
  trialLabel: string | null
  repoUrl: string
  recommendRank?: number
  ideaId?: string
}

export const storeProductCategories = [
  { id: "affiliate", label: "アフィリエイト・収益化" },
  { id: "seo-ops", label: "SEO・サイト運用" },
  { id: "resale", label: "せどり・買取・在庫" },
  { id: "hotel", label: "終電・ホテル・移動" },
  { id: "life-learn", label: "生活・学習・習慣化" },
  { id: "content", label: "コンテンツ制作" },
  { id: "realestate", label: "不動産・投資" },
  { id: "hobby", label: "趣味・推し活・地域" },
  { id: "b2b", label: "B2B・店舗・業務" },
] as const

/** おすすめ順（新規78）— store 先頭セクション用 */
export const recommendedNewProducts: StoreProduct[] = [
  {
    slug: "zero-conversion-sheet",
    category: "affiliate",
    emoji: "🩺",
    label: "クリックはあるのに成果ゼロ診断シート",
    sublabel: "ROOM・ASP成果の切り分け",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "スプレッドシート 買い切り",
    title: "クリックはあるのに成果ゼロ診断シート",
    description:
      "クリックはあるのに成果が出ないとき、リンク・投稿・商品・ROOM側のどこが弱いかをチェック項目で切り分ける診断シートです。",
    features: [
      "チェック項目で原因を言語化",
      "ROOM/ブログ両対応",
      "CSV取込前の事前診断に最適",
      "購入後すぐコピーして利用"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/zero-conversion-sheet",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-zero-conversion-sheet",
    recommendRank: 1,
    ideaId: "A10",
  },
  {
    slug: "rakuten-sale-eve-checklist",
    category: "affiliate",
    emoji: "🛒",
    label: "楽天スーパーセール前夜チェックリスト",
    sublabel: "セール前にやることを1枚で",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "チェックリスト 買い切り",
    title: "楽天スーパーセール前夜チェックリスト",
    description:
      "スーパーセール前夜にやる投稿・リンク・在庫・導線の確認項目をまとめた実践チェックリストです。",
    features: [
      "セール前の必須チェック",
      "ROOM/ブログ両対応",
      "季節ごとに使い回し可能",
      "PDF/Markdown同梱"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rakuten-sale-eve-checklist",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-rakuten-sale-eve-checklist",
    recommendRank: 2,
    ideaId: "A5",
  },
  {
    slug: "affiliate-disclosure-generator",
    category: "content",
    emoji: "⚖️",
    label: "アフィ開示文・PR表記ジェネレータ",
    sublabel: "表記漏れを防ぐ一文生成",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webツール 買い切り",
    title: "アフィ開示文・PR表記ジェネレータ",
    description:
      "媒体と案件種別に合わせて、アフィリエイト開示・PR表記の文案を生成するブラウザツールです。",
    features: [
      "媒体別の文案テンプレ",
      "ワンクリックコピー",
      "サーバー送信なし",
      "即デプロイ可能な静的HTML"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/affiliate-disclosure-generator",
    price: "¥280",
    priceNote: "¥280（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-affiliate-disclosure-generator",
    recommendRank: 3,
    ideaId: "G6",
  },
  {
    slug: "resale-profit-mini",
    category: "resale",
    emoji: "🧮",
    label: "せどり利益計算ミニアプリ",
    sublabel: "手数料プリセット付き",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "Webアプリ 買い切り",
    title: "せどり利益計算ミニアプリ",
    description:
      "仕入・販売・送料・各モール手数料から見込み利益をすぐ計算するスマホ向けミニアプリです。",
    features: [
      "メルカリ/Amazon等の手数料プリセット",
      "利益率の即表示",
      "端末内保存",
      "せどらーSへの入口にも"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/resale-profit-mini",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-resale-profit-mini",
    recommendRank: 4,
    ideaId: "B2",
  },
  {
    slug: "resale-tax-notebook",
    category: "resale",
    emoji: "🧾",
    label: "せどり確定申告メモ帳",
    sublabel: "仕入・売上・経費の年次メモ",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "スプレッドシート 買い切り",
    title: "せどり確定申告メモ帳",
    description:
      "せどりの仕入・売上・経費を年次で残し、確定申告前の整理をラクにするスプレッドシートテンプレートです。",
    features: [
      "月次入力→年次集計",
      "経費カテゴリ付き",
      "年末アップデート想定",
      "CSV雛形同梱"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/resale-tax-notebook",
    price: "¥780",
    priceNote: "¥780（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-resale-tax-notebook",
    recommendRank: 5,
    ideaId: "B6",
  },
  {
    slug: "missed-last-train-checklist",
    category: "hotel",
    emoji: "🌙",
    label: "終電逃した夜チェックリスト",
    sublabel: "今夜どうするかを1枚で",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "チェックリスト 買い切り",
    title: "終電逃した夜チェックリスト",
    description:
      "終電を逃した夜に、ホテル・代替施設・帰宅手段を落ち着いて選ぶためのチェックリストです。",
    features: [
      "判断の順番を固定",
      "終電ホテルサイトと併用",
      "超低単価の入口商材",
      "Markdown/PDF想定"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/missed-last-train-checklist",
    price: "¥280",
    priceNote: "¥280（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-missed-last-train-checklist",
    recommendRank: 6,
    ideaId: "C2",
  },
  {
    slug: "llms-txt-ai-citation-kit",
    category: "seo-ops",
    emoji: "🤖",
    label: "llms.txt / AI引用対策キット",
    sublabel: "AI検索・引用向けサイト整備",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "テンプレート 買い切り",
    title: "llms.txt / AI引用対策キット",
    description:
      "llms.txt、要約用メタ、引用されやすいFAQ構造の雛形と設置手順をまとめた個人開発者向けキットです。",
    features: [
      "llms.txt雛形",
      "FAQ構造化の例",
      "設置チェックリスト",
      "公開キットのアップセル"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/llms-txt-ai-citation-kit",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-llms-txt-ai-citation-kit",
    recommendRank: 7,
    ideaId: "D4",
  },
  {
    slug: "quiz-pack-takken-sharoushi",
    category: "life-learn",
    emoji: "📚",
    label: "資格問題パック（宅建・社労士）",
    sublabel: "AI Quiz / StudyLaw 横展開",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "問題パック 買い切り",
    title: "資格問題パック（宅建・社労士）",
    description:
      "宅建・社労士向けの一問一答・四択問題データパック。既存クイズアプリに流し込んで使えます。",
    features: [
      "JSON問題データ",
      "カテゴリ分け済み",
      "解説フィールド付き",
      "差し替え手順README"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/quiz-pack-takken-sharoushi",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-quiz-pack-takken-sharoushi",
    recommendRank: 8,
    ideaId: "E2",
  },
  {
    slug: "oshi-trip-planner",
    category: "hobby",
    emoji: "✨",
    label: "推し活遠征 終電・ホテル同梱プランナー",
    sublabel: "遠征×終電×宿の一体計画",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "Webアプリ 買い切り",
    title: "推し活遠征 終電・ホテル同梱プランナー",
    description:
      "イベント終了時刻・終電・ホテル条件を一画面で整理する、推し活遠征向けプランナーです。",
    features: [
      "終了時刻から逆算",
      "宿条件メモ",
      "チェックリスト出力",
      "終電ホテル導線と接続"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/oshi-trip-planner",
    price: "¥780",
    priceNote: "¥780（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-oshi-trip-planner",
    recommendRank: 9,
    ideaId: "I3",
  },
  {
    slug: "shuden-hotel-pro",
    category: "hotel",
    emoji: "🏨",
    label: "終電ホテル Pro（月額アラート）",
    sublabel: "終電前リマインド＆今夜の宿サマリー",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "月額アラート",
    title: "終電ホテル Pro（月額アラート）",
    description:
      "路線・駅のウォッチと終電前アラート、今夜のホテル候補サマリーを提供する個人向け月額プランです。",
    features: [
      "ウォッチ最大5件",
      "終電前通知",
      "今夜候補サマリー",
      "いつでも解約可（想定）"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/shuden-hotel-pro",
    price: "¥480/月",
    priceNote: "月額 ¥480/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-shuden-hotel-pro",
    recommendRank: 10,
    ideaId: "C1",
  },
  {
    slug: "rakuten-room-30day-calendar",
    category: "affiliate",
    emoji: "📅",
    label: "楽天ROOM 30日投稿カレンダー",
    sublabel: "投稿テーマ＋文例30日分",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "テンプレート 買い切り",
    title: "楽天ROOM 30日投稿カレンダー",
    description:
      "楽天ROOMを30日止めずに回すための投稿テーマ・文例カレンダーです。",
    features: [
      "30日分のテーマ",
      "文例つき",
      "セール週の差し替え欄",
      "ROOM改善ツールと併用可"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rakuten-room-30day-calendar",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-rakuten-room-30day-calendar",
    recommendRank: 11,
    ideaId: "A1",
  },
  {
    slug: "subscription-cancel-alert",
    category: "life-learn",
    emoji: "🔔",
    label: "サブスク解約忘れアラート",
    sublabel: "更新日前に通知",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "月額",
    title: "サブスク解約忘れアラート",
    description:
      "サブスクの更新日を登録し、解約忘れを防ぐ個人向けリマインダーです。",
    features: [
      "更新日リマインド",
      "金額メモ",
      "カテゴリ分け",
      "家計ツールと併売向き"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/subscription-cancel-alert",
    price: "¥300/月",
    priceNote: "月額 ¥300/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-subscription-cancel-alert",
    recommendRank: 12,
    ideaId: "E5",
  },
  {
    slug: "ga4-event-cheatsheet",
    category: "seo-ops",
    emoji: "📈",
    label: "GA4イベント設計チートシート",
    sublabel: "ブログ/比較/予約の計測設計",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "チートシート 買い切り",
    title: "GA4イベント設計チートシート",
    description:
      "ブログ・比較・予約サイト向けに、入れるべきGA4イベントと命名規則をまとめたチートシートです。",
    features: [
      "用途別イベント一覧",
      "命名規則",
      "実装チェック",
      "個人開発サイト向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/ga4-event-cheatsheet",
    price: "¥780",
    priceNote: "¥780（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-ga4-event-cheatsheet",
    recommendRank: 13,
    ideaId: "D2",
  },
  {
    slug: "84repo-ops-playbook",
    category: "seo-ops",
    emoji: "📦",
    label: "84リポ運用 公開プレイブック",
    sublabel: "多リポ個人開発の回し方",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "プレイブック",
    title: "84リポ運用 公開プレイブック",
    description:
      "多数リポジトリを抱えながら公開・計測・棚卸しする運用の型をまとめたプレイブックです。",
    features: [
      "公開チェックの型",
      "棚卸し周期",
      "計測の最低ライン",
      "RepoKuraとの併用"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/84repo-ops-playbook",
    price: "¥1,980",
    priceNote: "¥1,980（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-84repo-ops-playbook",
    recommendRank: 14,
    ideaId: "D7",
  },
  {
    slug: "release-notes-announcer",
    category: "content",
    emoji: "📣",
    label: "リリースノート→告知文3種変換",
    sublabel: "X / ブログ / BOOTH用",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webツール 買い切り",
    title: "リリースノート→告知文3種変換",
    description:
      "リリースノートを貼ると、X・ブログ・BOOTH向けの告知文3種を生成するツールです。",
    features: [
      "3媒体一括生成",
      "コピーボタン",
      "静的HTML",
      "個人開発のリリース儀式を短縮"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/release-notes-announcer",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-release-notes-announcer",
    recommendRank: 15,
    ideaId: "G2",
  },
  {
    slug: "hotel-listing-b2b",
    category: "b2b",
    emoji: "🛎️",
    label: "ホテル・簡易宿所の終電サイト掲載",
    sublabel: "終電ホテルへの店舗掲載",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 掲載",
    title: "ホテル・簡易宿所の終電サイト掲載",
    description:
      "終電・ホテル比較サイトへの宿泊施設掲載枠。計測付きの店舗ページを提供するB2Bメニューです。",
    features: [
      "店舗ページ",
      "問い合わせ導線",
      "掲載計測",
      "個人Proからの需要証明向き"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/hotel-listing-b2b",
    price: "¥5,000〜/月",
    priceNote: "¥5,000〜/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-hotel-listing-b2b",
    recommendRank: 16,
    ideaId: "H1",
  },
  {
    slug: "asp-listing-rules-checker",
    category: "affiliate",
    emoji: "✅",
    label: "アフィ案件 掲載条件チェッカー",
    sublabel: "規約・表記の漏れ防止",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "スプレッドシート 買い切り",
    title: "アフィ案件 掲載条件チェッカー",
    description:
      "ASP・案件ごとの掲載条件や表記ルールをチェックするスプレッドシートです。",
    features: [
      "案件別チェック欄",
      "表記必須項目",
      "差し止め予防",
      "週次運用向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/asp-listing-rules-checker",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-asp-listing-rules-checker",
    recommendRank: 17,
    ideaId: "A2",
  },
  {
    slug: "amazon-associate-review-kit",
    category: "affiliate",
    emoji: "📦",
    label: "Amazonアソシエイト 週次レビュー投稿キット",
    sublabel: "レビュー文・構成テンプレ",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "キット 買い切り",
    title: "Amazonアソシエイト 週次レビュー投稿キット",
    description:
      "Amazonアソシエイト向けに、週次で回せるレビュー構成と文例テンプレートを同梱したキットです。",
    features: [
      "構成テンプレ",
      "文例",
      "週次カレンダー",
      "楽天偏重の補完"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/amazon-associate-review-kit",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-amazon-associate-review-kit",
    recommendRank: 18,
    ideaId: "A3",
  },
  {
    slug: "blog-revenue-simulator",
    category: "affiliate",
    emoji: "💹",
    label: "ブログ収益シミュレーション",
    sublabel: "CTR→報酬の試算",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "Webアプリ 買い切り",
    title: "ブログ収益シミュレーション",
    description:
      "PV・CTR・承認率・単価から記事・サイトの見込み報酬を試算するシミュレータです。",
    features: [
      "ASP別パラメータ",
      "記事単位試算",
      "感度分析",
      "ブラウザ完結"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/blog-revenue-simulator",
    price: "¥1,480",
    priceNote: "¥1,480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-blog-revenue-simulator",
    recommendRank: 19,
    ideaId: "A4",
  },
  {
    slug: "room-erabiyori-playbook",
    category: "affiliate",
    emoji: "🔗",
    label: "楽天ROOM×えらびより 連携プレイブック",
    sublabel: "自社ツール横断の使い方",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "プレイブック",
    title: "楽天ROOM×えらびより 連携プレイブック",
    description:
      "えらびよりで候補を探し、ROOM改善ツールで投稿・診断する一連の流れをまとめたプレイブックです。",
    features: [
      "連携フロー図",
      "週次ルーチン",
      "事例メモ欄",
      "クロスセル用"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/room-erabiyori-playbook",
    price: "¥1,480",
    priceNote: "¥1,480（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-room-erabiyori-playbook",
    recommendRank: 20,
    ideaId: "A8",
  },
  {
    slug: "affiliate-first-10k-guide",
    category: "affiliate",
    emoji: "🎬",
    label: "副業アフィ 月1万円までの手順書",
    sublabel: "やり方から入る層向け",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "手順書・動画構成",
    title: "副業アフィ 月1万円までの手順書",
    description:
      "副業アフィリエイトで月1万円を目指す手順を、動画台本付きでまとめたコンテンツ商品です。",
    features: [
      "ステップ手順",
      "動画台本",
      "チェックリスト",
      "ツール導線付き"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/affiliate-first-10k-guide",
    price: "¥2,480",
    priceNote: "¥2,480（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-affiliate-first-10k-guide",
    recommendRank: 21,
    ideaId: "A9",
  },
  {
    slug: "resale-store-route-map",
    category: "resale",
    emoji: "🗺️",
    label: "店舗別 今日の仕入れルートマップ",
    sublabel: "店舗せどりの移動最適化",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "テンプレート 買い切り",
    title: "店舗別 今日の仕入れルートマップ",
    description:
      "今日回る買取・仕入れ店舗の順序とメモを残すルートマップテンプレートです。",
    features: [
      "店舗リスト",
      "ルート順",
      "仕入メモ",
      "日次利用"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/resale-store-route-map",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-resale-store-route-map",
    recommendRank: 22,
    ideaId: "B1",
  },
  {
    slug: "inventory-deadline-reminder",
    category: "resale",
    emoji: "⏰",
    label: "保管・出品期限リマインダー",
    sublabel: "置きっぱなし在庫を減らす",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "月額",
    title: "保管・出品期限リマインダー",
    description:
      "保管期限・出品期限を登録し、通知で回転を促すせどり向け月額リマインダーです。",
    features: [
      "期限登録",
      "通知想定",
      "SKUメモ",
      "在庫回転改善"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/inventory-deadline-reminder",
    price: "¥380/月",
    priceNote: "月額 ¥380/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-inventory-deadline-reminder",
    recommendRank: 23,
    ideaId: "B3",
  },
  {
    slug: "media-resale-condition-guide",
    category: "resale",
    emoji: "📀",
    label: "メディアせどり コンディション判定ガイド",
    sublabel: "DVD/CDの状態判定",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "ガイド",
    title: "メディアせどり コンディション判定ガイド",
    description:
      "DVD/CDのせどりで迷いがちなコンディション判定基準を写真例つきでまとめたガイドです。",
    features: [
      "判定基準表",
      "写真チェック観点",
      "JANツールと併用",
      "初心者向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/media-resale-condition-guide",
    price: "¥980",
    priceNote: "¥980（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-media-resale-condition-guide",
    recommendRank: 24,
    ideaId: "B4",
  },
  {
    slug: "jan-mercari-draft",
    category: "resale",
    emoji: "🏷️",
    label: "JAN一括→メルカリ下書き文生成",
    sublabel: "出品文の量産",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "Webアプリ 買い切り",
    title: "JAN一括→メルカリ下書き文生成",
    description:
      "JANや商品名の一覧からメルカリ向け下書き文を一括生成するツールです。",
    features: [
      "CSV/手入力対応",
      "文面テンプレ",
      "コピー出力",
      "出品ボトルネック解消"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/jan-mercari-draft",
    price: "¥1,480",
    priceNote: "¥1,480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-jan-mercari-draft",
    recommendRank: 25,
    ideaId: "B7",
  },
  {
    slug: "keepa-cheatsheet",
    category: "resale",
    emoji: "📉",
    label: "Keepa見方チートシート",
    sublabel: "グラフの読み方入門",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "チートシート 買い切り",
    title: "Keepa見方チートシート",
    description:
      "Keepaグラフの基本的な見方と仕入れ判断の観点を1枚にまとめたチートシートです。",
    features: [
      "指標の意味",
      "仕入れ判断の目安",
      "初心者向け",
      "低単価入口"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/keepa-cheatsheet",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-keepa-cheatsheet",
    recommendRank: 26,
    ideaId: "B10",
  },
  {
    slug: "line-lasttrain-hotel-notes",
    category: "hotel",
    emoji: "🚇",
    label: "路線別・終電後ホテル攻略ノート",
    sublabel: "路線×終電後の宿",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "攻略ノート",
    title: "路線別・終電後ホテル攻略ノート",
    description:
      "主要路線ごとに終電後のホテル・代替の考え方をまとめた攻略ノートです。",
    features: [
      "路線別メモ",
      "駅チカ観点",
      "サイト内部リンク向き",
      "PPV/ノート想定"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/line-lasttrain-hotel-notes",
    price: "¥500",
    priceNote: "¥500（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-line-lasttrain-hotel-notes",
    recommendRank: 27,
    ideaId: "C3",
  },
  {
    slug: "business-trip-pack",
    category: "hotel",
    emoji: "💼",
    label: "出張パック（終電＋ビジネスホテル）",
    sublabel: "出張者向け条件保存",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "月額",
    title: "出張パック（終電＋ビジネスホテル）",
    description:
      "出張時の終電条件とビジネスホテルの希望条件を保存し、毎回の探し直しを減らす月額パックです。",
    features: [
      "条件保存",
      "終電ウォッチ",
      "予算帯メモ",
      "個人事業主向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/business-trip-pack",
    price: "¥680/月",
    priceNote: "月額 ¥680/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-business-trip-pack",
    recommendRank: 28,
    ideaId: "C4",
  },
  {
    slug: "night-alternative-map",
    category: "hotel",
    emoji: "🗺️",
    label: "カプセル・サウナ・漫画喫茶の代替マップ",
    sublabel: "ホテル満室時の代替",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "Webアプリ 買い切り",
    title: "カプセル・サウナ・漫画喫茶の代替マップ",
    description:
      "終電後にホテルが取れないときのための、カプセル・サウナ・漫画喫茶などの代替候補マップです。",
    features: [
      "代替カテゴリ",
      "メモ登録",
      "エリア絞り込みUI",
      "終電導線の補完"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/night-alternative-map",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-night-alternative-map",
    recommendRank: 29,
    ideaId: "C8",
  },
  {
    slug: "event-end-alert",
    category: "hotel",
    emoji: "🎳",
    label: "イベント終了時刻連動アラート",
    sublabel: "ライブ・ボウリング向け",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "月額",
    title: "イベント終了時刻連動アラート",
    description:
      "イベント終了時刻から終電・移動を逆算して通知するアラート（ライブ・プロチャレンジ等）。",
    features: [
      "終了時刻登録",
      "終電逆算",
      "趣味導線接続",
      "月額通知"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/event-end-alert",
    price: "¥480/月",
    priceNote: "月額 ¥480/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-event-end-alert",
    recommendRank: 30,
    ideaId: "C10",
  },
  {
    slug: "indexnow-weekly-health",
    category: "seo-ops",
    emoji: "🩺",
    label: "IndexNow＋sitemap 週次健康診断",
    sublabel: "公開キットの継続版",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "月額",
    title: "IndexNow＋sitemap 週次健康診断",
    description:
      "sitemapとIndexNowの状態を週次で健康診断する個人開発者向け月額レポートです。",
    features: [
      "週次レポート想定",
      "sitemap確認観点",
      "IndexNow観点",
      "公開キット連携"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/indexnow-weekly-health",
    price: "¥480/月",
    priceNote: "月額 ¥480/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-indexnow-weekly-health",
    recommendRank: 31,
    ideaId: "D1",
  },
  {
    slug: "gsc-drop-weekly-mail",
    category: "seo-ops",
    emoji: "📉",
    label: "Search Console 急落週次メール",
    sublabel: "見ていないと気づかない下落",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "月額",
    title: "Search Console 急落週次メール",
    description:
      "Search Consoleのクリック/表示の急落を週次メールで知らせる監視サービス案です。",
    features: [
      "急落検知の考え方案",
      "週次メール",
      "複数プロパティ",
      "SEOダッシュボード連携"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/gsc-drop-weekly-mail",
    price: "¥680/月",
    priceNote: "月額 ¥680/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-gsc-drop-weekly-mail",
    recommendRank: 32,
    ideaId: "D3",
  },
  {
    slug: "vercel-bill-shock-checker",
    category: "seo-ops",
    emoji: "💸",
    label: "Vercel請求ショック防止チェッカー",
    sublabel: "帯域・関数の目安チェック",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "Webツール 買い切り",
    title: "Vercel請求ショック防止チェッカー",
    description:
      "PVや関数実行の見積から、Vercel請求が跳ねそうなポイントをチェックするツールです。",
    features: [
      "ざっくり見積",
      "注意閾値",
      "静的HTML",
      "多サイト運営者向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/vercel-bill-shock-checker",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-vercel-bill-shock-checker",
    recommendRank: 33,
    ideaId: "D6",
  },
  {
    slug: "comparison-site-starter",
    category: "seo-ops",
    emoji: "🧩",
    label: "比較サイト量産スターター（Next）",
    sublabel: "比較・ランキングサイトの型",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "Nextテンプレ 買い切り",
    title: "比較サイト量産スターター（Next）",
    description:
      "比較・ランキング系サイトを量産するためのNext.jsスターターテンプレートです。",
    features: [
      "一覧/詳細の型",
      "メタ設定例",
      "アフィカード部品",
      "CROSS-ASP系の製品化"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/comparison-site-starter",
    price: "¥2,980",
    priceNote: "¥2,980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-comparison-site-starter",
    recommendRank: 34,
    ideaId: "D8",
  },
  {
    slug: "ogp-favicon-kit",
    category: "seo-ops",
    emoji: "🖼️",
    label: "OGP・ファビコン一括生成キット",
    sublabel: "毎回やる単純作業を短縮",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "キット 買い切り",
    title: "OGP・ファビコン一括生成キット",
    description:
      "サイト名・色からOGP文言とファビコン用SVGの出発点を生成するキットです。",
    features: [
      "OGP文言生成",
      "SVGファビコン雛形",
      "サイズチェックリスト",
      "公開前の時短"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/ogp-favicon-kit",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-ogp-favicon-kit",
    recommendRank: 35,
    ideaId: "D10",
  },
  {
    slug: "structured-data-snippets",
    category: "seo-ops",
    emoji: "🧱",
    label: "構造化データ スニペット集",
    sublabel: "FAQ/Product/LocalBusiness",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "スニペット 買い切り",
    title: "構造化データ スニペット集",
    description:
      "FAQ・Product・LocalBusinessなど、よく使うJSON-LDスニペットを用途別にまとめた集です。",
    features: [
      "用途別JSON-LD",
      "貼り付け例",
      "検証チェック",
      "SEO実務向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/structured-data-snippets",
    price: "¥780",
    priceNote: "¥780（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-structured-data-snippets",
    recommendRank: 36,
    ideaId: "D11",
  },
  {
    slug: "exam-pace-maker",
    category: "life-learn",
    emoji: "🎯",
    label: "資格試験カウントダウン＋ペースメーカー",
    sublabel: "過去問ペース管理",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "月額",
    title: "資格試験カウントダウン＋ペースメーカー",
    description:
      "試験日から逆算した過去問ペースを管理する資格学習向け月額ツールです。",
    features: [
      "試験日カウントダウン",
      "週間ペース",
      "復習フラグ",
      "クイズアプリ連携想定"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/exam-pace-maker",
    price: "¥480/月",
    priceNote: "月額 ¥480/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-exam-pace-maker",
    recommendRank: 37,
    ideaId: "E1",
  },
  {
    slug: "sando-bozu-comeback-kit",
    category: "life-learn",
    emoji: "🔁",
    label: "三日坊主 復帰キット",
    sublabel: "GoalPilot連携の復帰手順",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "キット 買い切り",
    title: "三日坊主 復帰キット",
    description:
      "挫折したあとに戻る手順を短くまとめた復帰キット。GoalPilot利用者向けの補助教材です。",
    features: [
      "1分カムバック手順",
      "ご褒美設計メモ",
      "チェックリスト",
      "感情的購買に強い"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/sando-bozu-comeback-kit",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-sando-bozu-comeback-kit",
    recommendRank: 38,
    ideaId: "E3",
  },
  {
    slug: "medical-furusato-notebook",
    category: "life-learn",
    emoji: "🏥",
    label: "医療費控除・ふるさと納税メモ帳",
    sublabel: "年一の書類整理",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "スプレッドシート 買い切り",
    title: "医療費控除・ふるさと納税メモ帳",
    description:
      "医療費控除とふるさと納税の記録を年次で残すメモ帳テンプレートです。",
    features: [
      "領収メモ",
      "寄付先一覧",
      "年次集計",
      "確定申告前の整理"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/medical-furusato-notebook",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-medical-furusato-notebook",
    recommendRank: 39,
    ideaId: "E6",
  },
  {
    slug: "leave-home-checklist",
    category: "life-learn",
    emoji: "🚪",
    label: "出门前チェック（忘れもの防止）",
    sublabel: "出门前の確認リスト",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "Webアプリ 買い切り",
    title: "出门前チェック（忘れもの防止）",
    description:
      "鍵・財布・定期など、出门前に確認する項目をカスタムできるチェックアプリです。",
    features: [
      "カスタム項目",
      "ワンタップ完了",
      "端末内保存",
      "習慣系の定番ペルソナ"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/leave-home-checklist",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-leave-home-checklist",
    recommendRank: 40,
    ideaId: "E8",
  },
  {
    slug: "rent-market-watch",
    category: "realestate",
    emoji: "🏘️",
    label: "賃料相場ウォッチ（市区町村）",
    sublabel: "転居シーズン向け",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "月額",
    title: "賃料相場ウォッチ（市区町村）",
    description:
      "市区町村単位の賃料相場をウォッチし、変動を追う個人向け月額サービス案です。",
    features: [
      "エリア登録",
      "月次比較の型",
      "転居検討向け",
      "価格ウォッチの居住版"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rent-market-watch",
    price: "¥680/月",
    priceNote: "月額 ¥680/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-rent-market-watch",
    recommendRank: 41,
    ideaId: "F1",
  },
  {
    slug: "rent-vs-buy-simulator",
    category: "realestate",
    emoji: "🏠",
    label: "家賃vs購入 簡易シミュレータ",
    sublabel: "ざっくり比較",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "Webアプリ 買い切り",
    title: "家賃vs購入 簡易シミュレータ",
    description:
      "家賃・購入・金利・修繕などの前提を入れ、家賃継続と購入を比較する簡易シミュレータです。",
    features: [
      "前提パラメータ",
      "総額比較",
      "注意書き（助言ではない）",
      "ブラウザ完結"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rent-vs-buy-simulator",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-rent-vs-buy-simulator",
    recommendRank: 42,
    ideaId: "F2",
  },
  {
    slug: "relocation-cost-sheet",
    category: "realestate",
    emoji: "🌲",
    label: "地方移住コスト試算シート",
    sublabel: "移住前の費用見える化",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "スプレッドシート 買い切り",
    title: "地方移住コスト試算シート",
    description:
      "引っ越し・家賃差・交通・生活費など、地方移住のコストを試算するシートです。",
    features: [
      "費用カテゴリ",
      "月次/初期の分け",
      "比較メモ",
      "話題性のあるニッチ"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/relocation-cost-sheet",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-relocation-cost-sheet",
    recommendRank: 43,
    ideaId: "F6",
  },
  {
    slug: "x-thread-composer",
    category: "content",
    emoji: "🧵",
    label: "Xスレッド構成ジェネレータ",
    sublabel: "告知・解説スレの型",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webツール 買い切り",
    title: "Xスレッド構成ジェネレータ",
    description:
      "テーマを入れるとX（Twitter）スレッドの構成案を生成するツールです。",
    features: [
      "投稿分割案",
      "フック文案",
      "コピー",
      "個人開発の集客向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/x-thread-composer",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-x-thread-composer",
    recommendRank: 44,
    ideaId: "G1",
  },
  {
    slug: "booth-thumb-presets",
    category: "content",
    emoji: "🎨",
    label: "BOOTHサムネ文言・配色プリセット",
    sublabel: "出品画像の出発点",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "プリセット 買い切り",
    title: "BOOTHサムネ文言・配色プリセット",
    description:
      "BOOTH出品用のサムネ文言パターンと配色プリセットをまとめたキットです。",
    features: [
      "文言パターン",
      "配色例",
      "サイズ目安",
      "自社出品にも利用可"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/booth-thumb-presets",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-booth-thumb-presets",
    recommendRank: 45,
    ideaId: "G3",
  },
  {
    slug: "tsumiage-devlog-template",
    category: "content",
    emoji: "📝",
    label: "積み上げログ式 開発日記テンプレ",
    sublabel: "ブランドの型を売る",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "テンプレート 買い切り",
    title: "積み上げログ式 開発日記テンプレ",
    description:
      "積み上げログで使っている開発日記の書き方テンプレートです。",
    features: [
      "見出し構成",
      "振り返り欄",
      "公開チェック",
      "ブランド一貫"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/tsumiage-devlog-template",
    price: "¥280",
    priceNote: "¥280（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-tsumiage-devlog-template",
    recommendRank: 46,
    ideaId: "G5",
  },
  {
    slug: "buyback-shop-spotlight-b2b",
    category: "b2b",
    emoji: "💰",
    label: "買取店「本日の買取強化」枠",
    sublabel: "買取強化の日次枠",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 掲載",
    title: "買取店「本日の買取強化」枠",
    description:
      "買取価格比較・仕入れ系サイト上で、店舗の「本日の買取強化」を出すB2B掲載枠です。",
    features: [
      "日次枠",
      "JAN/カテゴリ指定",
      "問い合わせ導線",
      "Buyback系の裏表"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/buyback-shop-spotlight-b2b",
    price: "¥10,000/月",
    priceNote: "¥10,000/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-buyback-shop-spotlight-b2b",
    recommendRank: 47,
    ideaId: "H2",
  },
  {
    slug: "bowling-venue-listing-pro",
    category: "b2b",
    emoji: "🎳",
    label: "ボウリング場イベント掲載Pro",
    sublabel: "bowling-event.jp 向け",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 掲載",
    title: "ボウリング場イベント掲載Pro",
    description:
      "ボウリング場のプロチャレンジ等イベントを優先掲載する会場向けProプランです。",
    features: [
      "イベント掲載",
      "会場ページ",
      "更新導線",
      "趣味サイト monetize"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/bowling-venue-listing-pro",
    price: "¥3,000〜/月",
    priceNote: "¥3,000〜/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-bowling-venue-listing-pro",
    recommendRank: 48,
    ideaId: "H3",
  },
  {
    slug: "site-health-audit-service",
    category: "b2b",
    emoji: "🔍",
    label: "サイト健康診断（単発）",
    sublabel: "個人開発者向け監査",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "単発サービス",
    title: "サイト健康診断（単発）",
    description:
      "SEO・計測・公開設定を単発で診断するサービスメニュー（公開キットの上位）。",
    features: [
      "診断項目リスト",
      "報告書テンプレ",
      "改善優先度",
      "キットへの導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/site-health-audit-service",
    price: "¥9,800/件",
    priceNote: "¥9,800/件 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-site-health-audit-service",
    recommendRank: 49,
    ideaId: "H7",
  },
  {
    slug: "pro-challenge-checklist",
    category: "hobby",
    emoji: "🏆",
    label: "プロチャレンジ参戦チェックリスト",
    sublabel: "当日までの準備",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "チェックリスト 買い切り",
    title: "プロチャレンジ参戦チェックリスト",
    description:
      "ボウリングのプロチャレンジ参戦に向けた持ち物・予約・当日の流れのチェックリストです。",
    features: [
      "事前準備",
      "当日動線",
      "実体験ベース",
      "趣味信頼"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/pro-challenge-checklist",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-pro-challenge-checklist",
    recommendRank: 50,
    ideaId: "I1",
  },
  {
    slug: "affiliate-rewrite-brief",
    category: "affiliate",
    emoji: "✍️",
    label: "アフィ記事リライト指示書ジェネレータ",
    sublabel: "SEO停滞記事の立て直し",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "Webツール 買い切り",
    title: "アフィ記事リライト指示書ジェネレータ",
    description:
      "テーマと現状課題を入れると、アフィ記事のリライト指示書を生成するツールです。",
    features: [
      "指示書自動生成",
      "検索意図欄",
      "CTA設計",
      "content-brief姉妹"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/affiliate-rewrite-brief",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-affiliate-rewrite-brief",
    recommendRank: 51,
    ideaId: "A6",
  },
  {
    slug: "asp-denial-casebook",
    category: "affiliate",
    emoji: "📕",
    label: "ASP別 否認パターン事例集",
    sublabel: "不安を減らす教材",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "事例集",
    title: "ASP別 否認パターン事例集",
    description:
      "アフィリエイト成果否認で起きやすいパターンをASP横断で整理した事例集です。",
    features: [
      "パターン分類",
      "予防チェック",
      "年1更新想定",
      "不安商材"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/asp-denial-casebook",
    price: "¥1,980",
    priceNote: "¥1,980（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-asp-denial-casebook",
    recommendRank: 52,
    ideaId: "A7",
  },
  {
    slug: "buyback-ocr-table",
    category: "resale",
    emoji: "🖼️",
    label: "買取店価格スクショ→表変換",
    sublabel: "手集計の苦痛を減らす",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "Webツール 買い切り",
    title: "買取店価格スクショ→表変換",
    description:
      "買取価格表のスクショやテキストから、比較用テーブルへ落とし込む支援ツールです。",
    features: [
      "テキスト整形",
      "表プレビュー",
      "CSV出力",
      "手作業削減"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/buyback-ocr-table",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-buyback-ocr-table",
    recommendRank: 53,
    ideaId: "B5",
  },
  {
    slug: "loss-sku-flag-sheet",
    category: "resale",
    emoji: "🚩",
    label: "赤字SKU 自動フラグシート",
    sublabel: "在庫回転の可視化",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "スプレッドシート 買い切り",
    title: "赤字SKU 自動フラグシート",
    description:
      "仕入と売価から赤字・滞留SKUにフラグを立てる在庫管理シートです。",
    features: [
      "利益フラグ",
      "滞留日数",
      "処分候補リスト",
      "回転改善"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/loss-sku-flag-sheet",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-loss-sku-flag-sheet",
    recommendRank: 54,
    ideaId: "B8",
  },
  {
    slug: "store-photo-organizer",
    category: "resale",
    emoji: "📷",
    label: "店舗せどり写真フォルダ整理",
    sublabel: "撮影枚数が多い人向け",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "ルール＋スクリプト",
    title: "店舗せどり写真フォルダ整理",
    description:
      "店舗せどりで撮った写真を日付・店舗・JANで整理するためのフォルダルールと補助スクリプトです。",
    features: [
      "命名規則",
      "フォルダ雛形",
      "整理スクリプト例",
      "出品前の時短"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/store-photo-organizer",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-store-photo-organizer",
    recommendRank: 55,
    ideaId: "B9",
  },
  {
    slug: "nomikai-season-alert",
    category: "hotel",
    emoji: "🍻",
    label: "飲み会シーズン終電アラート",
    sublabel: "忘年会・歓送迎会",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "期間限定月額",
    title: "飲み会シーズン終電アラート",
    description:
      "飲み会シーズン向けに、終電前リマインドを強調した期間限定月額アラートです。",
    features: [
      "季節訴求",
      "終電前通知",
      "低価格",
      "終電ホテル導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/nomikai-season-alert",
    price: "¥300/月",
    priceNote: "月額 ¥300/月（税込目安）| 準備中→公開",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-nomikai-season-alert",
    recommendRank: 56,
    ideaId: "C5",
  },
  {
    slug: "station-hotel-walk-report",
    category: "hotel",
    emoji: "🚶",
    label: "駅チカホテル 徒歩分検証レポート",
    sublabel: "実歩測の信頼コンテンツ",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "PPVレポート",
    title: "駅チカホテル 徒歩分検証レポート",
    description:
      "駅からの実徒歩分を検証したホテルレポート（PPV想定）のテンプレート＆サンプルです。",
    features: [
      "検証フォーマット",
      "サンプル1本",
      "UGC的信頼",
      "路線ノート連動"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/station-hotel-walk-report",
    price: "¥480",
    priceNote: "¥480（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-station-hotel-walk-report",
    recommendRank: 57,
    ideaId: "C6",
  },
  {
    slug: "hotel-listing-cms",
    category: "b2b",
    emoji: "🗂️",
    label: "ホテル掲載枠CMS（店舗ページ＋計測）",
    sublabel: "掲載運用の裏側",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B CMS",
    title: "ホテル掲載枠CMS（店舗ページ＋計測）",
    description:
      "ホテル掲載枠を運用するための店舗ページCMSと簡易計測のスターターです。",
    features: [
      "店舗CRUDの型",
      "計測イベント案",
      "公開ページ雛形",
      "H1の実装基盤"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/hotel-listing-cms",
    price: "¥5,000〜/月",
    priceNote: "¥5,000〜/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-hotel-listing-cms",
    recommendRank: 58,
    ideaId: "C7",
  },
  {
    slug: "lasttrain-taxi-compare",
    category: "hotel",
    emoji: "🚕",
    label: "終電＋タクシー概算 帰るvs泊まる",
    sublabel: "意思決定の比較",
    gradient: "linear-gradient(135deg, #1e3a5f 0%, #0f172a 100%)",
    badge: "Webアプリ 買い切り",
    title: "終電＋タクシー概算 帰るvs泊まる",
    description:
      "終電帰宅（タクシー含む）とホテル宿泊の概算コストを比べる比較ツールです。",
    features: [
      "概算入力",
      "比較表示",
      "注意書き",
      "終電サイト導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/lasttrain-taxi-compare",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-lasttrain-taxi-compare",
    recommendRank: 59,
    ideaId: "C9",
  },
  {
    slug: "domain-expiry-calendar",
    category: "seo-ops",
    emoji: "🌐",
    label: "ドメイン棚卸し＋更新期限カレンダー",
    sublabel: "多サイト運営者向け",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "テンプレート 買い切り",
    title: "ドメイン棚卸し＋更新期限カレンダー",
    description:
      "保有ドメインの更新期限・DNS・用途を一覧化する棚卸しカレンダーです。",
    features: [
      "更新期限",
      "用途メモ",
      "移管メモ",
      "多サイト向け"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/domain-expiry-calendar",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-domain-expiry-calendar",
    recommendRank: 60,
    ideaId: "D5",
  },
  {
    slug: "safe-niche-list",
    category: "seo-ops",
    emoji: "🧭",
    label: "安全ニッチリスト（アダルト除外済み）",
    sublabel: "サイト選定の時短",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "リスト 買い切り",
    title: "安全ニッチリスト（アダルト除外済み）",
    description:
      "個人開発・アフィで扱いやすい安全寄りのニッチ候補を整理したリストです（アダルト除外）。",
    features: [
      "ニッチ候補",
      "切り口例",
      "注意ジャンル",
      "選定時短"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/safe-niche-list",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-safe-niche-list",
    recommendRank: 61,
    ideaId: "D9",
  },
  {
    slug: "launch-90day-kpi",
    category: "seo-ops",
    emoji: "📊",
    label: "個人開発 公開90日KPIシート",
    sublabel: "公開後の数字管理",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "スプレッドシート 買い切り",
    title: "個人開発 公開90日KPIシート",
    description:
      "サイト公開後90日のPV・登録・収益KPIを追うシートです。",
    features: [
      "週次KPI",
      "仮説メモ",
      "振り返り欄",
      "GoalPilot的な開発者版"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/launch-90day-kpi",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-launch-90day-kpi",
    recommendRank: 62,
    ideaId: "D12",
  },
  {
    slug: "fridge-loss-sheet",
    category: "life-learn",
    emoji: "🥬",
    label: "食材ロス削減・冷蔵庫在庫シート",
    sublabel: "時短レシピの隣接",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "スプレッドシート 買い切り",
    title: "食材ロス削減・冷蔵庫在庫シート",
    description:
      "冷蔵庫の在庫と消費期限を書き、ロスを減らすための在庫シートです。",
    features: [
      "在庫一覧",
      "期限",
      "使い切りメモ",
      "レシピツール併売"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/fridge-loss-sheet",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-fridge-loss-sheet",
    recommendRank: 63,
    ideaId: "E4",
  },
  {
    slug: "commute-quiz-timer",
    category: "life-learn",
    emoji: "🚆",
    label: "通勤スキマ学習タイマー＋クイズ",
    sublabel: "通勤時間の一問一答",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "Webアプリ 買い切り",
    title: "通勤スキマ学習タイマー＋クイズ",
    description:
      "通勤時間に合わせた学習タイマーと、短問クイズを回すアプリです。",
    features: [
      "分数タイマー",
      "短問UI",
      "連続記録",
      "資格アプリ導線"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/commute-quiz-timer",
    price: "¥680",
    priceNote: "¥680（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-commute-quiz-timer",
    recommendRank: 64,
    ideaId: "E7",
  },
  {
    slug: "sleep-debt-calendar",
    category: "life-learn",
    emoji: "😴",
    label: "睡眠負債カレンダー",
    sublabel: "単純記録",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "Webアプリ 買い切り",
    title: "睡眠負債カレンダー",
    description:
      "睡眠時間を記録し、ざっくりとした睡眠負債を可視化するカレンダーアプリです。",
    features: [
      "日次記録",
      "週次合計",
      "端末内保存",
      "低開発コスト商品"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/sleep-debt-calendar",
    price: "¥380",
    priceNote: "¥380（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-sleep-debt-calendar",
    recommendRank: 65,
    ideaId: "E9",
  },
  {
    slug: "oshi-catcafe-spend-log",
    category: "hobby",
    emoji: "🐱",
    label: "猫カフェ・推し活支出ログ",
    sublabel: "趣味家計",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "スプレッドシート 買い切り",
    title: "猫カフェ・推し活支出ログ",
    description:
      "推し活・猫カフェなど趣味支出を記録する家計ログテンプレートです。",
    features: [
      "カテゴリ別支出",
      "月次集計",
      "イベントメモ",
      "PPV趣味と一貫"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/oshi-catcafe-spend-log",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-oshi-catcafe-spend-log",
    recommendRank: 66,
    ideaId: "E10",
  },
  {
    slug: "condo-fee-guide",
    category: "realestate",
    emoji: "🏢",
    label: "管理費・修繕積立の見え方ガイド",
    sublabel: "購入検討者の不安対策",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "ガイド",
    title: "管理費・修繕積立の見え方ガイド",
    description:
      "マンション購入時に見るべき管理費・修繕積立の観点をまとめたガイドです。",
    features: [
      "見るべき項目",
      "注意サイン",
      "質問リスト",
      "投資助言ではない旨"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/condo-fee-guide",
    price: "¥780",
    priceNote: "¥780（税込目安）| 講座・PPV・ガイド",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-condo-fee-guide",
    recommendRank: 67,
    ideaId: "F3",
  },
  {
    slug: "akiya-transfer-checklist",
    category: "realestate",
    emoji: "🏚️",
    label: "空き家・譲渡の基礎チェックリスト",
    sublabel: "手続きの全体像",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "チェックリスト 買い切り",
    title: "空き家・譲渡の基礎チェックリスト",
    description:
      "空き家の譲渡・整理で確認したい基礎項目のチェックリストです。",
    features: [
      "関係者確認",
      "書類メモ",
      "次アクション",
      "行政データ系と相性"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/akiya-transfer-checklist",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-akiya-transfer-checklist",
    recommendRank: 68,
    ideaId: "F4",
  },
  {
    slug: "local-shop-finder-template",
    category: "realestate",
    emoji: "🏪",
    label: "地元店舗の探し方テンプレ",
    sublabel: "まちリスト系の型",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "テンプレート 買い切り",
    title: "地元店舗の探し方テンプレ",
    description:
      "地域の店舗・スポットを調べてまとめるための探し方・掲載テンプレートです。",
    features: [
      "調査手順",
      "掲載項目",
      "カテゴリ例",
      "machi-list資産の製品化"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/local-shop-finder-template",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-local-shop-finder-template",
    recommendRank: 69,
    ideaId: "F5",
  },
  {
    slug: "blog-to-short-script",
    category: "content",
    emoji: "🎥",
    label: "ブログ→ショート動画台本変換",
    sublabel: "ストック記事の再利用",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webツール 買い切り",
    title: "ブログ→ショート動画台本変換",
    description:
      "ブログ記事を貼ると、ショート動画向けの台本構成に変換するツールです。",
    features: [
      "章立て変換",
      "尺目安",
      "フック案",
      "再利用"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/blog-to-short-script",
    price: "¥980",
    priceNote: "¥980（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-blog-to-short-script",
    recommendRank: 70,
    ideaId: "G4",
  },
  {
    slug: "jan-inventory-widget-b2b",
    category: "b2b",
    emoji: "📡",
    label: "店舗向けJAN在庫公開ウィジェット",
    sublabel: "dvd-jan の法人版",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B",
    title: "店舗向けJAN在庫公開ウィジェット",
    description:
      "店舗のJAN在庫をサイトに埋め込める公開ウィジェットのB2Bメニュー／スターターです。",
    features: [
      "埋め込みsnippet案",
      "在庫APIの型",
      "店舗向け",
      "DVD JAN連動"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/jan-inventory-widget-b2b",
    price: "¥4,800/月",
    priceNote: "¥4,800/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-jan-inventory-widget-b2b",
    recommendRank: 71,
    ideaId: "H4",
  },
  {
    slug: "local-seo-monthly-report",
    category: "b2b",
    emoji: "📑",
    label: "地域店舗 SEO月刊レポート代行",
    sublabel: "高単価・手厚い",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 代行",
    title: "地域店舗 SEO月刊レポート代行",
    description:
      "地域店舗向けにSEO状況を月刊レポートする代行サービスメニューです。",
    features: [
      "レポート雛形",
      "改善提案欄",
      "打ち合わせアジェンダ",
      "高単価"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/local-seo-monthly-report",
    price: "¥15,000/月",
    priceNote: "¥15,000/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-local-seo-monthly-report",
    recommendRank: 72,
    ideaId: "H5",
  },
  {
    slug: "sauna-manga-night-ad",
    category: "b2b",
    emoji: "♨️",
    label: "サウナ・漫画喫茶の終電後枠広告",
    sublabel: "終電後の代替施設",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 広告枠",
    title: "サウナ・漫画喫茶の終電後枠広告",
    description:
      "終電後の代替マップ上に出す、サウナ・漫画喫茶向け広告枠メニューです。",
    features: [
      "枠メニュー",
      "掲載仕様",
      "代替マップ連動",
      "夜間需要"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/sauna-manga-night-ad",
    price: "¥8,000/月",
    priceNote: "¥8,000/月 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-sauna-manga-night-ad",
    recommendRank: 73,
    ideaId: "H6",
  },
  {
    slug: "resale-school-whitelabel",
    category: "b2b",
    emoji: "🏫",
    label: "せどりスクール向けツール白ラベル",
    sublabel: "sedora 系の法人提供",
    gradient: "linear-gradient(135deg, #334155 0%, #0f172a 100%)",
    badge: "B2B 白ラベル",
    title: "せどりスクール向けツール白ラベル",
    description:
      "せどりスクール・コミュニティ向けに査定ツールを白ラベル提供するための提案・構成キットです。",
    features: [
      "提供範囲の型",
      "料金テーブル案",
      "オンボーディング",
      "sedora連動"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/resale-school-whitelabel",
    price: "要見積",
    priceNote: "要見積 | B2B・掲載・代行 | 問い合わせ準備中",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-resale-school-whitelabel",
    recommendRank: 74,
    ideaId: "H8",
  },
  {
    slug: "retro-cafe-map-kit",
    category: "hobby",
    emoji: "☕",
    label: "レトロ喫茶マップ作り方キット",
    sublabel: "PPV連動の趣味コンテンツ",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "キット 買い切り",
    title: "レトロ喫茶マップ作り方キット",
    description:
      "レトロ喫茶を調べてマップ化する手順とテンプレートのキットです。",
    features: [
      "調査手順",
      "マップ項目",
      "写真の撮り方",
      "趣味PPV連動"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/retro-cafe-map-kit",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-retro-cafe-map-kit",
    recommendRank: 75,
    ideaId: "I2",
  },
  {
    slug: "cat-goods-room-examples",
    category: "hobby",
    emoji: "😺",
    label: "猫用品アフィ ROOM文例50",
    sublabel: "楽天ROOM×趣味",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "文例集 買い切り",
    title: "猫用品アフィ ROOM文例50",
    description:
      "猫用品アフィリエイト向けの楽天ROOM投稿文例50本です。",
    features: [
      "文例50",
      "カテゴリ分け",
      "開示文セット",
      "ROOMツール併売"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/cat-goods-room-examples",
    price: "¥480",
    priceNote: "¥480（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-cat-goods-room-examples",
    recommendRank: 76,
    ideaId: "I4",
  },
  {
    slug: "chita-local-spots-db",
    category: "hobby",
    emoji: "🌏",
    label: "知多半島 地元スポットDB雛形",
    sublabel: "知多丸ブランドの原点",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "DB雛形 買い切り",
    title: "知多半島 地元スポットDB雛形",
    description:
      "知多半島の地元スポットを蓄積するためのデータ雛形と収集ルールです。",
    features: [
      "スポットスキーマ",
      "カテゴリ例",
      "収集ルール",
      "地域ブランド"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/chita-local-spots-db",
    price: "¥580",
    priceNote: "¥580（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-chita-local-spots-db",
    recommendRank: 77,
    ideaId: "I5",
  },
  {
    slug: "dev-focus-bgm-timer",
    category: "hobby",
    emoji: "🎧",
    label: "作業BGMプレイリスト＋集中タイマー",
    sublabel: "開発配信・作業用",
    gradient: "linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)",
    badge: "Webアプリ 買い切り",
    title: "作業BGMプレイリスト＋集中タイマー",
    description:
      "作業用の集中タイマーとBGMプレイリストメモを組み合わせた小さなツールです。",
    features: [
      "ポモドーロ風タイマー",
      "プレイリストメモ",
      "静的HTML",
      "ノベルティ向き"
    ],
    boothUrl: "https://chitamaru.booth.pm/items/dev-focus-bgm-timer",
    price: "¥280",
    priceNote: "¥280（税込目安）| 知多丸 / BOOTH販売予定",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/chitamaru-dev-focus-bgm-timer",
    recommendRank: 78,
    ideaId: "I6",
  },
]

/** 全製品（既存ライン + 新規）。カテゴリ表示はこちらを使用 */
export const storeProducts: StoreProduct[] = [
  // ── 既存16製品 ──
] = [
  // ── アフィリエイト・収益化 ──
  {
    slug: "rakuafi-tool",
    category: "affiliate",
    emoji: "📊",
    label: "楽天ROOMクリック改善ツール",
    sublabel: "投稿文生成 + 報酬ゼロ診断",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "Webアプリ 買い切り",
    title: "楽天ROOMクリック改善ツール PRO版",
    description:
      "投稿文の自動生成、商品別リンク診断、クリック・報酬データの記録、報酬ゼロ原因の自動言語化まで。楽天ROOM運用をブラウザ1画面で完結させる買い切りツールです。",
    features: [
      "ROOM投稿文をワンタップで自動生成",
      "汎用リンク vs 商品別リンクを自動診断",
      "楽天アフィリエイトCSVをグラフで可視化",
      "データはブラウザ内保存・サーバー送信なし",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rakuafi-tool",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| 購入後に合言葉をお伝えします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/rakuafi-tool",
  },
  {
    slug: "raku-toolv2",
    category: "affiliate",
    emoji: "🗺️",
    label: "えらびより（楽天横断検索）",
    sublabel: "市場・トラベル・ブックス・Kobo・GORA",
    gradient: "linear-gradient(135deg, #bf0000 0%, #7a0000 100%)",
    badge: "Webアプリ 買い切り",
    title: "えらびより — 楽天アフィリエイト横断検索ツール",
    description:
      "楽天Web Serviceの5 API（市場・トラベル・ブックス・Kobo・GORA）を横断検索し、紹介候補の保存・投稿メモ化・UGCレビューまで行えるアフィリエイト検証ツールです。",
    features: [
      "楽天5 APIを1画面で横断検索",
      "候補保存・広告表記付き投稿メモ生成",
      "JSON-LD・sitemap・llms.txt 対応済み",
      "Access Keyをブラウザに露出しない安全設計",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/raku-toolv2",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| 楽天WSのアプリID・Access Keyが必要です",
    trialUrl: "https://erabiyori.jp/",
    trialLabel: "デモを見る ↗",
    repoUrl: "https://github.com/syunnjack/raku-toolv2",
  },
  {
    slug: "affiliate-logbook",
    category: "affiliate",
    emoji: "📋",
    label: "副業アフィリエイト 週次収支ログブック",
    sublabel: "複数ASP × Googleスプレッドシート",
    gradient: "linear-gradient(135deg, #16a34a 0%, #065f46 100%)",
    badge: "スプレッドシート 買い切り",
    title: "副業アフィリエイト 週次収支ログブック",
    description:
      "楽天・Amazon・A8など複数ASPの週次収益をまとめて記録し、「どのコンテンツが稼いでいるか」を1枚で把握できるGoogleスプレッドシートテンプレートです。",
    features: [
      "ASP別 週次クリック・承認・報酬を一括入力",
      "月別・ASP別サマリーを自動集計",
      "コンテンツ別貢献度シートで強化点が一目瞭然",
      "購入後すぐにコピーして使えるURL提供",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/affiliate-logbook",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）| GoogleスプレッドシートのコピーURLをお渡しします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack",
  },

  // ── SEO・サイト運用 ──
  {
    slug: "seo-dashboard-pro",
    category: "seo-ops",
    emoji: "🔍",
    label: "SEO管理ダッシュボード Pro",
    sublabel: "Search Console + GA4 を一画面で",
    gradient: "linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)",
    badge: "ソフトウェア 買い切り",
    title: "SEO管理ダッシュボード Pro",
    description:
      "GoogleアカウントでログインするだけでSearch ConsoleとGA4の全プロパティを一画面に表示。サイトマップ送信・測定IDコピー・プロパティへの直接リンクが即座に行えます。",
    features: [
      "全SCプロパティを自動取得・一覧表示",
      "GA4測定IDをワンクリックでコピー",
      "サイトマップの確認・送信がその場で完結",
      "Google OAuthによる安全な認証",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/seo-dashboard-pro",
    price: "¥3,800",
    priceNote: "買い切り ¥3,800（税込）| Google OAuthの設定が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack",
  },
  {
    slug: "site-launch-kit",
    category: "seo-ops",
    emoji: "🚀",
    label: "個人開発サイト公開キット",
    sublabel: "SEO・GA4・IndexNow 一括設定",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)",
    badge: "テンプレート 買い切り",
    title: "個人開発サイト公開キット",
    description:
      "Next.js/Vite/静的サイト向けに、SEOメタタグ、GA4、Search Console、IndexNow、sitemap、robots.txtを一括設定するパッチセットと公開前チェックリスト30項目が付属します。",
    features: [
      "Next.js / Vite / 静的サイト対応テンプレート",
      "GitHub Actions workflow（IndexNow自動送信）",
      "公開前チェックリストPDF 30項目",
      "shudenhotel.jp等5サイトで実際に使った手順",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/site-launch-kit",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| テンプレート一式 + PDF 即ダウンロード",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/rakuten02",
  },
  {
    slug: "togo-kanri-tool",
    category: "seo-ops",
    emoji: "📦",
    label: "RepoKura（レポクラ）",
    sublabel: "GitHub × Vercel リポジトリ棚卸し",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "Webアプリ 買い切り",
    title: "RepoKura — リポジトリ棚卸し管理ツール",
    description:
      "GitHubリポジトリとVercel公開先を毎日照合し、未デプロイ・未完成・重複を自動分類。GSC・GA4分析も内蔵。84件規模の個人開発ポートフォリオ運用に最適です。",
    features: [
      "デプロイし忘れ・未完成・重複を4分類で自動棚卸し",
      "毎日06:00（JST）のVercel Cron自動実行",
      "GSC・GA4サイト分析機能を内蔵",
      "PWA対応（PC・スマホにインストール可能）",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/togo-kanri-tool",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| GitHub・Vercel・Supabaseの設定が必要です",
    trialUrl: "https://togo-kanri-tool.vercel.app/",
    trialLabel: "デモを見る ↗",
    repoUrl: "https://github.com/syunnjack/togo-kanri-tool",
  },

  // ── せどり・買取・在庫 ──
  {
    slug: "sedora-s",
    category: "resale",
    emoji: "📀",
    label: "JAN・ISBN一括査定ツール",
    sublabel: "Windows デスクトップ / せどり向け",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "Windowsアプリ 買い切り",
    title: "JAN・ISBN・DVD作品検索（せどらーS）",
    description:
      "USBバーコードリーダーでJAN/ISBNを読み取り、楽天・Keepa相場と仕入利益を即計算。書籍・DVD・ゲーム・フィギュアの最安値・中央値・推奨販売価格を自動判定するWindowsデスクトップツールです。",
    features: [
      "キーボード入力型バーコードリーダー対応",
      "楽天市場 + Amazon（Keepa）相場を自動集計",
      "仕入額・手数料・送料から見込み利益を計算",
      "駿河屋・アニメイト等へのJAN引き継ぎ検索",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/sedora-s",
    price: "¥3,800",
    priceNote: "買い切り ¥3,800（税込）| Windows 10/11 + WebView2 Runtime が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/sedora-s",
  },
  {
    slug: "dvd-jan-scan-db",
    category: "resale",
    emoji: "📱",
    label: "DVD JAN Scan DB",
    sublabel: "スマホスキャン × PostgreSQL",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    badge: "Web + Android 買い切り",
    title: "DVD JAN Scan DB（dvdjan.jp）",
    description:
      "スマホカメラでDVD/Blu-rayのJANをスキャンし、楽天ブックスと照合してPostgreSQLに保存。買取リード・在庫管理・CSV出力まで対応するWeb＋Androidアプリです。",
    features: [
      "ブラウザのバーコードAPIで即スキャン",
      "楽天ブックス実データと自動照合",
      "PostgreSQL + Prismaで在庫を永続管理",
      "CapacitorでGoogle Play配布にも対応",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/dvd-jan-scan-db",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| PostgreSQL・楽天APIの設定が必要です",
    trialUrl: "https://dvdjan.jp/",
    trialLabel: "サイトを見る ↗",
    repoUrl: "https://github.com/syunnjack/dvd-jan-scan-db",
  },
  {
    slug: "buyback-price-alert",
    category: "resale",
    emoji: "💰",
    label: "BuybackAlert",
    sublabel: "店舗間価格差ランキング",
    gradient: "linear-gradient(135deg, #ca8a04 0%, #854d0e 100%)",
    badge: "Webアプリ 買い切り",
    title: "BuybackAlert — 仕入れ価格差アラート",
    description:
      "同一JANの店舗間販売価格差を集計し、最安値と中央値の差が大きい順にランキング表示。本・DVD・ゲーム・フィギュアの仕入れ候補を絞り込むためのツールです。",
    features: [
      "Yahoo!ショッピングの出品者別実価格を集計",
      "楽天ブックス価格も一部対応",
      "バーコードスキャンで即検索",
      "価格差ランキングで仕入れ候補を可視化",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/buyback-price-alert",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| Yahoo!ショッピング APIの設定が必要です",
    trialUrl: "https://buybackalert.jp/",
    trialLabel: "サイトを見る ↗",
    repoUrl: "https://github.com/syunnjack/buyback-price-alert",
  },

  // ── 生活・学習・習慣化 ──
  {
    slug: "jitan-recipe",
    category: "life-learn",
    emoji: "🍳",
    label: "時短レシピ支援アプリ",
    sublabel: "楽天レシピ × 食材費概算",
    gradient: "linear-gradient(135deg, #f97316 0%, #ef4444 100%)",
    badge: "Webアプリ 買い切り",
    title: "時短レシピ支援アプリ",
    description:
      "楽天レシピから今日の料理を選ぶだけ。必要な食材リストと金額の概算がすぐに確認できます。食材ごとのチェックボックスで買い物リストとしても使えます。",
    features: [
      "楽天レシピ人気ランキングをカテゴリ別に表示",
      "食材ごとの金額概算を自動表示",
      "買い物チェックリスト機能付き",
      "調理時間・節約順にソート可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/jitan-recipe",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）",
    trialUrl: "/tools/recipe",
    trialLabel: "無料で試す →",
    repoUrl: "https://github.com/syunnjack/jitan-recipe",
  },
  {
    slug: "goal-pilot-app",
    category: "life-learn",
    emoji: "🎯",
    label: "GoalPilot",
    sublabel: "挫折前提の目標達成アプリ",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)",
    badge: "Web + Android 買い切り",
    title: "GoalPilot — 目標達成アプリ",
    description:
      "三日坊主を前提に設計した目標達成アプリ。逆算スケジュール、3分スタート、復帰モード、ご褒美設計、挫折リスクの可視化で「戻れる仕組み」を提供します。",
    features: [
      "無料3日間のやめがち診断",
      "逆算スケジュール + 3分スタート機能",
      "挫折後の復帰モード（1分カムバック）",
      "Capacitor Androidアプリ対応",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/goal-pilot-app",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）",
    trialUrl: "https://goalpilot.jp/",
    trialLabel: "無料版を試す ↗",
    repoUrl: "https://github.com/syunnjack/goal-pilot-app",
  },
  {
    slug: "receipt-jp",
    category: "life-learn",
    emoji: "🧾",
    label: "レシート家計簿",
    sublabel: "Claude API × OCR自動分類",
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    badge: "Webアプリ 買い切り",
    title: "レシート家計簿（receipt-jp）",
    description:
      "レシート画像をアップロードすると、Claude APIが商品名・金額・日付を自動読み取り、食費・日用品・外食などカテゴリ別に分類・集計する家計簿Webアプリです。",
    features: [
      "レシート画像 → Claude APIで自動OCR",
      "カテゴリ別（食費・日用品等）の自動分類",
      "Chart.jsによる円グラフ・月別棒グラフ",
      "APIキーはサーバー側のみ（ブラウザに露出しない）",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/receipt-jp",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| Anthropic APIキーが必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/receipt-jp",
  },
  {
    slug: "ai-quiz-study",
    category: "life-learn",
    emoji: "📚",
    label: "AI Quiz Study",
    sublabel: "資格一問一答 + AI解説",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "Webアプリ 買い切り",
    title: "AI Quiz Study — 資格一問一答アプリ",
    description:
      "行政書士などの資格を一問一答形式で学べる学習アプリ。AI解説・弱点復習・連続学習記録・LINE通知で継続をサポートします。",
    features: [
      "一問ずつ集中して解くUI設計",
      "間違えた問題にAI解説を自動付与",
      "弱点分野の振り返り・復習モード",
      "静的ビルドで高速・低コスト運用",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/ai-quiz-study",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| 問題データのカスタマイズ方法を同梱",
    trialUrl: "https://syunnjack.github.io/ai-quiz-study/",
    trialLabel: "デモを試す ↗",
    repoUrl: "https://github.com/syunnjack/ai-quiz-study",
  },
  {
    slug: "studylaw-app",
    category: "life-learn",
    emoji: "⚖️",
    label: "StudyLaw App",
    sublabel: "Laravel製 四択クイズテンプレート",
    gradient: "linear-gradient(135deg, #475569 0%, #1e293b 100%)",
    badge: "Laravelテンプレ 買い切り",
    title: "StudyLaw App — 資格クイズアプリテンプレート",
    description:
      "法律分野をカテゴリ別に学べるLaravel製四択クイズアプリ。カテゴリ管理・正誤判定・解説表示・スコア集計が実装済み。他資格への転用テンプレートとして使えます。",
    features: [
      "カテゴリ一覧・問題数表示",
      "回答後の正誤判定と解説表示",
      "Laravel 12 + SQLite/MySQL対応",
      "シーダー・テスト付きで即カスタマイズ可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/studylaw-app",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| PHP 8.2+ / Composer が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/studylaw-app",
  },

  // ── コンテンツ制作 ──
  {
    slug: "content-brief-engine",
    category: "content",
    emoji: "✍️",
    label: "コンテンツブリーフ生成エンジン",
    sublabel: "テーマ入力 → ブリーフ草案",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webアプリ 買い切り",
    title: "コンテンツブリーフ生成エンジン",
    description:
      "テーマ・読者・検索意図・CTAを入力するだけで、コンテンツ制作チーム向けのブリーフ草案を自動生成する静的Webアプリです。ライター・マーケ担当者向け。",
    features: [
      "テーマ・読者・目的・チャネル・検索意図を入力",
      "ブリーフ本文をワンクリックで自動生成",
      "生成結果のコピー機能付き",
      "Vite静的ビルドで即デプロイ可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/content-brief-engine",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）| ソースコード一式をお渡しします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/content-brief-engine",
  },

  // ── 不動産・投資 ──
  {
    slug: "fudousan-kakaku-watch",
    category: "realestate",
    emoji: "🏠",
    label: "不動産価格ウォッチ",
    sublabel: "国交省データ × LINE通知",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "Laravelアプリ 買い切り",
    title: "不動産価格ウォッチ",
    description:
      "国土交通省の不動産取引価格情報を都道府県別に表示し、前四半期比の変動と参考家賃を試算。LINE通知でウォッチ登録できるLaravelアプリです。",
    features: [
      "都道府県別の平均㎡単価と前四半期比",
      "期待利回りからの参考家賃試算",
      "LINEログインによるウォッチ登録・新着通知",
      "sitemap.xml配信・SEO対応済み",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/fudousan-kakaku-watch",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| LINE Login・MySQLの設定が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/fudousan-kakaku-watch",
  },
  // ── 新規おすすめ製品 ──
  ...recommendedNewProducts,
]

