export interface StoreProduct {
  slug: string
  category: string
  emoji: string
  label: string
  sublabel: string
  gradient: string
  badge: string
  title: string
  description: string
  features: string[]
  boothUrl: string
  price: string
  priceNote: string
  trialUrl: string | null
  trialLabel: string | null
  repoUrl: string
}

export const storeProductCategories = [
  { id: "affiliate", label: "アフィリエイト・収益化" },
  { id: "seo-ops", label: "SEO・サイト運用" },
  { id: "resale", label: "せどり・買取・在庫" },
  { id: "life-learn", label: "生活・学習・習慣化" },
  { id: "content", label: "コンテンツ制作" },
  { id: "realestate", label: "不動産・投資" },
] as const

export const storeProducts: StoreProduct[] = [
  // ── アフィリエイト・収益化 ──
  {
    slug: "rakuafi-tool",
    category: "affiliate",
    emoji: "📊",
    label: "楽天ROOMクリック改善ツール",
    sublabel: "投稿文生成 + 報酬ゼロ診断",
    gradient: "linear-gradient(135deg, #a02b36 0%, #6b0f1a 100%)",
    badge: "Webアプリ 買い切り",
    title: "楽天ROOMクリック改善ツール PRO版",
    description:
      "投稿文の自動生成、商品別リンク診断、クリック・報酬データの記録、報酬ゼロ原因の自動言語化まで。楽天ROOM運用をブラウザ1画面で完結させる買い切りツールです。",
    features: [
      "ROOM投稿文をワンタップで自動生成",
      "汎用リンク vs 商品別リンクを自動診断",
      "楽天アフィリエイトCSVをグラフで可視化",
      "データはブラウザ内保存・サーバー送信なし",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/rakuafi-tool",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| 購入後に合言葉をお伝えします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/rakuafi-tool",
  },
  {
    slug: "raku-toolv2",
    category: "affiliate",
    emoji: "🗺️",
    label: "えらびより（楽天横断検索）",
    sublabel: "市場・トラベル・ブックス・Kobo・GORA",
    gradient: "linear-gradient(135deg, #bf0000 0%, #7a0000 100%)",
    badge: "Webアプリ 買い切り",
    title: "えらびより — 楽天アフィリエイト横断検索ツール",
    description:
      "楽天Web Serviceの5 API（市場・トラベル・ブックス・Kobo・GORA）を横断検索し、紹介候補の保存・投稿メモ化・UGCレビューまで行えるアフィリエイト検証ツールです。",
    features: [
      "楽天5 APIを1画面で横断検索",
      "候補保存・広告表記付き投稿メモ生成",
      "JSON-LD・sitemap・llms.txt 対応済み",
      "Access Keyをブラウザに露出しない安全設計",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/raku-toolv2",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| 楽天WSのアプリID・Access Keyが必要です",
    trialUrl: "https://erabiyori.jp/",
    trialLabel: "デモを見る ↗",
    repoUrl: "https://github.com/syunnjack/raku-toolv2",
  },
  {
    slug: "affiliate-logbook",
    category: "affiliate",
    emoji: "📋",
    label: "副業アフィリエイト 週次収支ログブック",
    sublabel: "複数ASP × Googleスプレッドシート",
    gradient: "linear-gradient(135deg, #16a34a 0%, #065f46 100%)",
    badge: "スプレッドシート 買い切り",
    title: "副業アフィリエイト 週次収支ログブック",
    description:
      "楽天・Amazon・A8など複数ASPの週次収益をまとめて記録し、「どのコンテンツが稼いでいるか」を1枚で把握できるGoogleスプレッドシートテンプレートです。",
    features: [
      "ASP別 週次クリック・承認・報酬を一括入力",
      "月別・ASP別サマリーを自動集計",
      "コンテンツ別貢献度シートで強化点が一目瞭然",
      "購入後すぐにコピーして使えるURL提供",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/affiliate-logbook",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）| GoogleスプレッドシートのコピーURLをお渡しします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack",
  },

  // ── SEO・サイト運用 ──
  {
    slug: "seo-dashboard-pro",
    category: "seo-ops",
    emoji: "🔍",
    label: "SEO管理ダッシュボード Pro",
    sublabel: "Search Console + GA4 を一画面で",
    gradient: "linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)",
    badge: "ソフトウェア 買い切り",
    title: "SEO管理ダッシュボード Pro",
    description:
      "GoogleアカウントでログインするだけでSearch ConsoleとGA4の全プロパティを一画面に表示。サイトマップ送信・測定IDコピー・プロパティへの直接リンクが即座に行えます。",
    features: [
      "全SCプロパティを自動取得・一覧表示",
      "GA4測定IDをワンクリックでコピー",
      "サイトマップの確認・送信がその場で完結",
      "Google OAuthによる安全な認証",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/seo-dashboard-pro",
    price: "¥3,800",
    priceNote: "買い切り ¥3,800（税込）| Google OAuthの設定が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack",
  },
  {
    slug: "site-launch-kit",
    category: "seo-ops",
    emoji: "🚀",
    label: "個人開発サイト公開キット",
    sublabel: "SEO・GA4・IndexNow 一括設定",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #4c1d95 100%)",
    badge: "テンプレート 買い切り",
    title: "個人開発サイト公開キット",
    description:
      "Next.js/Vite/静的サイト向けに、SEOメタタグ、GA4、Search Console、IndexNow、sitemap、robots.txtを一括設定するパッチセットと公開前チェックリスト30項目が付属します。",
    features: [
      "Next.js / Vite / 静的サイト対応テンプレート",
      "GitHub Actions workflow（IndexNow自動送信）",
      "公開前チェックリストPDF 30項目",
      "shudenhotel.jp等5サイトで実際に使った手順",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/site-launch-kit",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| テンプレート一式 + PDF 即ダウンロード",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/rakuten02",
  },
  {
    slug: "togo-kanri-tool",
    category: "seo-ops",
    emoji: "📦",
    label: "RepoKura（レポクラ）",
    sublabel: "GitHub × Vercel リポジトリ棚卸し",
    gradient: "linear-gradient(135deg, #0f766e 0%, #134e4a 100%)",
    badge: "Webアプリ 買い切り",
    title: "RepoKura — リポジトリ棚卸し管理ツール",
    description:
      "GitHubリポジトリとVercel公開先を毎日照合し、未デプロイ・未完成・重複を自動分類。GSC・GA4分析も内蔵。84件規模の個人開発ポートフォリオ運用に最適です。",
    features: [
      "デプロイし忘れ・未完成・重複を4分類で自動棚卸し",
      "毎日06:00（JST）のVercel Cron自動実行",
      "GSC・GA4サイト分析機能を内蔵",
      "PWA対応（PC・スマホにインストール可能）",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/togo-kanri-tool",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| GitHub・Vercel・Supabaseの設定が必要です",
    trialUrl: "https://togo-kanri-tool.vercel.app/",
    trialLabel: "デモを見る ↗",
    repoUrl: "https://github.com/syunnjack/togo-kanri-tool",
  },

  // ── せどり・買取・在庫 ──
  {
    slug: "sedora-s",
    category: "resale",
    emoji: "📀",
    label: "JAN・ISBN一括査定ツール",
    sublabel: "Windows デスクトップ / せどり向け",
    gradient: "linear-gradient(135deg, #b45309 0%, #78350f 100%)",
    badge: "Windowsアプリ 買い切り",
    title: "JAN・ISBN・DVD作品検索（せどらーS）",
    description:
      "USBバーコードリーダーでJAN/ISBNを読み取り、楽天・Keepa相場と仕入利益を即計算。書籍・DVD・ゲーム・フィギュアの最安値・中央値・推奨販売価格を自動判定するWindowsデスクトップツールです。",
    features: [
      "キーボード入力型バーコードリーダー対応",
      "楽天市場 + Amazon（Keepa）相場を自動集計",
      "仕入額・手数料・送料から見込み利益を計算",
      "駿河屋・アニメイト等へのJAN引き継ぎ検索",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/sedora-s",
    price: "¥3,800",
    priceNote: "買い切り ¥3,800（税込）| Windows 10/11 + WebView2 Runtime が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/sedora-s",
  },
  {
    slug: "dvd-jan-scan-db",
    category: "resale",
    emoji: "📱",
    label: "DVD JAN Scan DB",
    sublabel: "スマホスキャン × PostgreSQL",
    gradient: "linear-gradient(135deg, #1d4ed8 0%, #1e3a8a 100%)",
    badge: "Web + Android 買い切り",
    title: "DVD JAN Scan DB（dvdjan.jp）",
    description:
      "スマホカメラでDVD/Blu-rayのJANをスキャンし、楽天ブックスと照合してPostgreSQLに保存。買取リード・在庫管理・CSV出力まで対応するWeb＋Androidアプリです。",
    features: [
      "ブラウザのバーコードAPIで即スキャン",
      "楽天ブックス実データと自動照合",
      "PostgreSQL + Prismaで在庫を永続管理",
      "CapacitorでGoogle Play配布にも対応",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/dvd-jan-scan-db",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| PostgreSQL・楽天APIの設定が必要です",
    trialUrl: "https://dvdjan.jp/",
    trialLabel: "サイトを見る ↗",
    repoUrl: "https://github.com/syunnjack/dvd-jan-scan-db",
  },
  {
    slug: "buyback-price-alert",
    category: "resale",
    emoji: "💰",
    label: "BuybackAlert",
    sublabel: "店舗間価格差ランキング",
    gradient: "linear-gradient(135deg, #ca8a04 0%, #854d0e 100%)",
    badge: "Webアプリ 買い切り",
    title: "BuybackAlert — 仕入れ価格差アラート",
    description:
      "同一JANの店舗間販売価格差を集計し、最安値と中央値の差が大きい順にランキング表示。本・DVD・ゲーム・フィギュアの仕入れ候補を絞り込むためのツールです。",
    features: [
      "Yahoo!ショッピングの出品者別実価格を集計",
      "楽天ブックス価格も一部対応",
      "バーコードスキャンで即検索",
      "価格差ランキングで仕入れ候補を可視化",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/buyback-price-alert",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| Yahoo!ショッピング APIの設定が必要です",
    trialUrl: "https://buybackalert.jp/",
    trialLabel: "サイトを見る ↗",
    repoUrl: "https://github.com/syunnjack/buyback-price-alert",
  },

  // ── 生活・学習・習慣化 ──
  {
    slug: "jitan-recipe",
    category: "life-learn",
    emoji: "🍳",
    label: "時短レシピ支援アプリ",
    sublabel: "楽天レシピ × 食材費概算",
    gradient: "linear-gradient(135deg, #f97316 0%, #ef4444 100%)",
    badge: "Webアプリ 買い切り",
    title: "時短レシピ支援アプリ",
    description:
      "楽天レシピから今日の料理を選ぶだけ。必要な食材リストと金額の概算がすぐに確認できます。食材ごとのチェックボックスで買い物リストとしても使えます。",
    features: [
      "楽天レシピ人気ランキングをカテゴリ別に表示",
      "食材ごとの金額概算を自動表示",
      "買い物チェックリスト機能付き",
      "調理時間・節約順にソート可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/jitan-recipe",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）",
    trialUrl: "/tools/recipe",
    trialLabel: "無料で試す →",
    repoUrl: "https://github.com/syunnjack/jitan-recipe",
  },
  {
    slug: "goal-pilot-app",
    category: "life-learn",
    emoji: "🎯",
    label: "GoalPilot",
    sublabel: "挫折前提の目標達成アプリ",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)",
    badge: "Web + Android 買い切り",
    title: "GoalPilot — 目標達成アプリ",
    description:
      "三日坊主を前提に設計した目標達成アプリ。逆算スケジュール、3分スタート、復帰モード、ご褒美設計、挫折リスクの可視化で「戻れる仕組み」を提供します。",
    features: [
      "無料3日間のやめがち診断",
      "逆算スケジュール + 3分スタート機能",
      "挫折後の復帰モード（1分カムバック）",
      "Capacitor Androidアプリ対応",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/goal-pilot-app",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）",
    trialUrl: "https://goalpilot.jp/",
    trialLabel: "無料版を試す ↗",
    repoUrl: "https://github.com/syunnjack/goal-pilot-app",
  },
  {
    slug: "receipt-jp",
    category: "life-learn",
    emoji: "🧾",
    label: "レシート家計簿",
    sublabel: "Claude API × OCR自動分類",
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)",
    badge: "Webアプリ 買い切り",
    title: "レシート家計簿（receipt-jp）",
    description:
      "レシート画像をアップロードすると、Claude APIが商品名・金額・日付を自動読み取り、食費・日用品・外食などカテゴリ別に分類・集計する家計簿Webアプリです。",
    features: [
      "レシート画像 → Claude APIで自動OCR",
      "カテゴリ別（食費・日用品等）の自動分類",
      "Chart.jsによる円グラフ・月別棒グラフ",
      "APIキーはサーバー側のみ（ブラウザに露出しない）",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/receipt-jp",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| Anthropic APIキーが必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/receipt-jp",
  },
  {
    slug: "ai-quiz-study",
    category: "life-learn",
    emoji: "📚",
    label: "AI Quiz Study",
    sublabel: "資格一問一答 + AI解説",
    gradient: "linear-gradient(135deg, #2563eb 0%, #1e40af 100%)",
    badge: "Webアプリ 買い切り",
    title: "AI Quiz Study — 資格一問一答アプリ",
    description:
      "行政書士などの資格を一問一答形式で学べる学習アプリ。AI解説・弱点復習・連続学習記録・LINE通知で継続をサポートします。",
    features: [
      "一問ずつ集中して解くUI設計",
      "間違えた問題にAI解説を自動付与",
      "弱点分野の振り返り・復習モード",
      "静的ビルドで高速・低コスト運用",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/ai-quiz-study",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| 問題データのカスタマイズ方法を同梱",
    trialUrl: "https://syunnjack.github.io/ai-quiz-study/",
    trialLabel: "デモを試す ↗",
    repoUrl: "https://github.com/syunnjack/ai-quiz-study",
  },
  {
    slug: "studylaw-app",
    category: "life-learn",
    emoji: "⚖️",
    label: "StudyLaw App",
    sublabel: "Laravel製 四択クイズテンプレート",
    gradient: "linear-gradient(135deg, #475569 0%, #1e293b 100%)",
    badge: "Laravelテンプレ 買い切り",
    title: "StudyLaw App — 資格クイズアプリテンプレート",
    description:
      "法律分野をカテゴリ別に学べるLaravel製四択クイズアプリ。カテゴリ管理・正誤判定・解説表示・スコア集計が実装済み。他資格への転用テンプレートとして使えます。",
    features: [
      "カテゴリ一覧・問題数表示",
      "回答後の正誤判定と解説表示",
      "Laravel 12 + SQLite/MySQL対応",
      "シーダー・テスト付きで即カスタマイズ可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/studylaw-app",
    price: "¥980",
    priceNote: "買い切り ¥980（税込）| PHP 8.2+ / Composer が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/studylaw-app",
  },

  // ── コンテンツ制作 ──
  {
    slug: "content-brief-engine",
    category: "content",
    emoji: "✍️",
    label: "コンテンツブリーフ生成エンジン",
    sublabel: "テーマ入力 → ブリーフ草案",
    gradient: "linear-gradient(135deg, #db2777 0%, #9d174d 100%)",
    badge: "Webアプリ 買い切り",
    title: "コンテンツブリーフ生成エンジン",
    description:
      "テーマ・読者・検索意図・CTAを入力するだけで、コンテンツ制作チーム向けのブリーフ草案を自動生成する静的Webアプリです。ライター・マーケ担当者向け。",
    features: [
      "テーマ・読者・目的・チャネル・検索意図を入力",
      "ブリーフ本文をワンクリックで自動生成",
      "生成結果のコピー機能付き",
      "Vite静的ビルドで即デプロイ可能",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/content-brief-engine",
    price: "¥580",
    priceNote: "買い切り ¥580（税込）| ソースコード一式をお渡しします",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/content-brief-engine",
  },

  // ── 不動産・投資 ──
  {
    slug: "fudousan-kakaku-watch",
    category: "realestate",
    emoji: "🏠",
    label: "不動産価格ウォッチ",
    sublabel: "国交省データ × LINE通知",
    gradient: "linear-gradient(135deg, #0369a1 0%, #0c4a6e 100%)",
    badge: "Laravelアプリ 買い切り",
    title: "不動産価格ウォッチ",
    description:
      "国土交通省の不動産取引価格情報を都道府県別に表示し、前四半期比の変動と参考家賃を試算。LINE通知でウォッチ登録できるLaravelアプリです。",
    features: [
      "都道府県別の平均㎡単価と前四半期比",
      "期待利回りからの参考家賃試算",
      "LINEログインによるウォッチ登録・新着通知",
      "sitemap.xml配信・SEO対応済み",
    ],
    boothUrl: "https://chitamaru.booth.pm/items/fudousan-kakaku-watch",
    price: "¥2,480",
    priceNote: "買い切り ¥2,480（税込）| LINE Login・MySQLの設定が必要です",
    trialUrl: null,
    trialLabel: null,
    repoUrl: "https://github.com/syunnjack/fudousan-kakaku-watch",
  },
]
